UPDATE pages SET content = '[
  {"id":"hero","type":"component","data":{"component":"HeroSection","badge":"Loved by 25,000+ local businesses","title":"The All-in-One Platform to Manage & Grow Your Local Business","subtitle":"Optimize your Google Business Profile, monitor reviews, manage listings, and get actionable insights — all from one powerful dashboard.","ctaPrimaryText":"Start Free Trial","ctaPrimaryLink":"/pricing","ctaSecondaryText":"Book a Demo","ctaSecondaryLink":"/contact"}},
  {"id":"logos","type":"component","data":{"component":"LogoTicker","heading":"Trusted by businesses managing their presence on","logos":[{"name":"Google"},{"name":"Yelp"},{"name":"Facebook"},{"name":"TripAdvisor"},{"name":"Apple Maps"},{"name":"Bing"},{"name":"Foursquare"},{"name":"Trustpilot"},{"name":"BBB"},{"name":"Citysearch"}]}},
  {"id":"features","type":"component","data":{"component":"FeaturesCarousel","title":"Everything You Need to Dominate Local Search","subtitle":"A complete suite of tools to manage your online presence and grow your business.","features":[{"icon":"MapPin","title":"GBP Management","desc":"Update info, photos, and attributes across all locations from one dashboard."},{"icon":"Star","title":"Review Monitoring","desc":"Track, respond to, and analyze reviews from Google and 50+ platforms."},{"icon":"FileText","title":"Listings Management","desc":"Ensure consistent NAP data across all major directories."},{"icon":"BarChart3","title":"Analytics & Insights","desc":"Track profile views, search queries, and customer actions in real-time."},{"icon":"Megaphone","title":"Posts & Updates","desc":"Schedule and publish posts directly to your Google Business Profile."}]}},
  {"id":"howitworks","type":"component","data":{"component":"HowItWorks","title":"How It Works","subtitle":"Get started in minutes with three simple steps.","steps":[{"icon":"UserPlus","title":"Connect Your Profiles","desc":"Link your Google Business Profiles in seconds. We support unlimited locations."},{"icon":"Settings","title":"Optimize & Manage","desc":"Update business info, respond to reviews, publish posts, and fix listings — all in one place."},{"icon":"TrendingUp","title":"Grow & Track Results","desc":"Watch your visibility climb with detailed analytics and actionable insights."}]}},
  {"id":"benefits","type":"component","data":{"component":"BenefitsGrid","title":"Why Choose GMB Briefcase?","subtitle":"Built for agencies and businesses that take local marketing seriously.","benefits":[{"icon":"Clock","title":"Save Time","desc":"Manage all locations from a single dashboard. No more switching tabs."},{"icon":"TrendingUp","title":"Boost Rankings","desc":"Optimize your profiles to rank higher in local search results."},{"icon":"MessageSquare","title":"Manage Reviews","desc":"Monitor and respond to reviews across 50+ platforms instantly."},{"icon":"Building2","title":"Multi-Location Support","desc":"Scale effortlessly whether you have 1 or 1,000 locations."},{"icon":"Brain","title":"AI-Powered Insights","desc":"Get smart recommendations to improve your local presence."},{"icon":"Search","title":"Competitor Analysis","desc":"See how you stack up against competitors in your area."}]}},
  {"id":"screenshot","type":"component","data":{"component":"ProductScreenshot","title":"Your Command Center for Local Marketing","subtitle":"See everything at a glance — from reviews and rankings to posts and performance."}},
  {"id":"testimonials","type":"component","data":{"component":"TestimonialsCarousel","title":"What Our Customers Say","testimonials":[{"name":"Sarah Johnson","company":"Johnson Dental Group","quote":"GMB Briefcase saved us 15+ hours a week managing our 12 locations. The review monitoring alone is worth it.","rating":5,"avatar":"SJ"},{"name":"Michael Chen","company":"Bay Area Auto Repair","quote":"We saw a 40% increase in phone calls within the first month. The analytics make it easy to see what is working.","rating":5,"avatar":"MC"},{"name":"Emily Rodriguez","company":"Fresh Bites Restaurants","quote":"Managing posts and reviews across all our locations used to be a nightmare. Now it is a breeze.","rating":5,"avatar":"ER"},{"name":"David Kim","company":"Kim Legal Associates","quote":"The competitor analysis feature helped us identify gaps and outrank competing firms in our area.","rating":5,"avatar":"DK"}]}},
  {"id":"stats","type":"component","data":{"component":"StatsBar","stats":[{"value":10000,"suffix":"+","label":"Businesses"},{"value":5,"suffix":"M+","label":"Reviews Managed"},{"value":50,"suffix":"+","label":"Integrations"},{"value":99,"suffix":"%","label":"Uptime"}]}},
  {"id":"cta","type":"component","data":{"component":"CTABanner","title":"Take Your Business to the Next Level","subtitle":"Join 10,000+ businesses already using GMB Briefcase to dominate local search.","ctaPrimaryText":"Start Free Trial","ctaPrimaryLink":"/pricing","ctaSecondaryText":"Talk to Sales","ctaSecondaryLink":"/contact"}}
]'::jsonb, updated_at = now()
WHERE slug = 'home';