// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otzjzbwoetkhlpxvgnag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90emp6YndvZXRraGxweHZnbmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMzE3NzIsImV4cCI6MjA4NzgwNzc3Mn0.Mla_GqpJrYWF5mT0OaOwLPaNpM_kcUjVjJ70lnvjwsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});